site_name: TerraMe

theme: 
  name: material
  palette:
    - scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7
        name: Modo noturno
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: modo claro


markdown_extensions:
  - pymdownx.tasklist # Lista de tarefas
  - pymdownx.emoji # Emojis
  - pymdownx.mark # Marcações
  - pymdownx.tilde # Tachado
  - pymdownx.highlight # código
  - pymdownx.superfences #bloquinho