site_name: TerraME 




theme: 
  name: readthedocs
  custom_dir: overrides
  logo: img/terramee.png
  site_favicon: img/favicon.ico
  highlightjs: true

  

nav:
  - 'index.md'




  
markdown_extensions:
  
  #pymdown
  - pymdownx.tasklist # Lista de tarefas
  - pymdownx.emoji # Emojis
  - pymdownx.mark # Marcações
  - pymdownx.tilde # Tachado
  - pymdownx.highlight # código
  - pymdownx.superfences #bloquinho


copyright: Copyright &copy; 2023 TerraME